apiVersion: v1
kind: Pod
metadta:
 name: pod-tolerated
spec:
 containers:
  - name: nginx
    image: nginx
 tolerations:
  - key: "project"
    operator: "Equal"
    value: "roboshop"
    effect: "NoSchedule"
